### ISSUE TITLE
let find_points() and find_intervals() return NA labels by default.

### ISSUE THREAD

**Issue by Teebusch** [patrickreidy/textgRid#3]
The functions drop all annotations (intervals and points) with `NA` labels because the default for the  `pattern` argument (used by grep) is `"*"`. 

Instead the functions should by default match *all* intervals and points. Otherwise it will not return (arguably very common) unlabeled points (these may be used e.g. when there is only one type of event in a tier, let's say "conversational turns". The label can then be specified in the tier name, so an additional label for each point is unnecessary). It also does not find unlabeled intervals (which e.g. may be a way to code silence). 

This behavior also creates problems further down the line with `as.data.frame()` so that the `NA` labeled intervals and points are not present in the data frame. This essentially is a loss of information, because the gaps (at least the gaps at the beginning and end of the tiers) cannot be reliably reconstructed from the data frame. This also means that a TextGrid constructor for data frames will not be able to reconstruct the original TextGrid, i.e. for a textgrid object x it will not be possible to guarantee that `TextGrid(as.data.frame(x)) == x` 

It is always easy for the user to filter `NA` elements later, but it shouldn't be a default that cannot be circumvented.

Grep will never match `NA`, regardless of the pattern, so the default has to be `pattern = NULL` or the like, so that grep can be done conditional on whether a pattern is supplied (e.g. `if(is.null(pattern))`) or not.

Example of behavior:
```r
textgrid <- TextGrid(system.file('extdata', 'myExample.TextGrid', 
                                 package = 'textgRid'))

findPoints(textgrid@.Data[[3]])
# Index Time      Label
# 1     1 6.75  voicingOn
# 2     2 8.25 voicingOff

textgrid@.Data[[3]]@labels[1] <- NA # set 1st label to NA

findPoints(textgrid@.Data[[3]])
# Index Time      Label
# 1     2 8.25 voicingOff
```

**Comment by Teebusch** [comment]
After looking at the code some more I wonder whether there is a compelling reason to treat empty labels as `NA` to begin with? It seems that it would be better to treat them as empty strings instead. This can be easily achieved by setting the default argument `miss = ""` in `.Extract()`

 Again it's very easy for the user to use the `pattern` argument to filter empty strings, or filter them afterwards, but it's hard to reconstruct intervals that `findIntervals`, `findPoints` and `as.data.frame` drop without asking.

**Comment by patrickreidy** [comment]
Thank you for making these fixes, Tobias. I've merged your pull request, so I will close this issue.
