### ISSUE TITLE
TextGrid with tabs gives an error

### ISSUE THREAD

**Issue by csapot** [patrickreidy/textgRid#7]
If I try to open a TextGrid file which containts tabulars instead of 4 spaces, there is an error message:

```
Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
  zero-length inputs cannot be mixed with those of non-zero length
```

If I replace the tabs with 4 spaces (in a text editor), opening the TextGrid file is OK.

[20170113_S_park_01_szajpad_0002_speech_TextGrid.txt](https://github.com/patrickreidy/textgRid/files/2061960/20170113_S_park_01_szajpad_0002_speech_TextGrid.txt)

**Comment by sebsau** [comment]
I get the same error message. However, my TextGrid does not contain any tabs.

**Comment by csapot** [comment]
I think it depends on the Praat version...

From the documentation, it is not clear how it should be: http://www.fon.hum.uva.nl/praat/manual/TextGrid_file_formats.html

**Comment by patrickreidy** [comment]
Sorry for the delay in attending to this bug. I've been at a conference, and then on vacation.

I hadn't realized that some versions of Praat prefix lines with spaces while others do so with tabs. This bug has been fixed.
